services:
  backend:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: deployment/Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
