"""
backend/app/database/models.py
--------------------------------
SQLAlchemy ORM model for the ``resources`` table.

Requires: sqlalchemy>=2.0  (pip install sqlalchemy)

This table stores metadata for every ingested resource (URL or PDF).
The raw content, chunks, and vector embeddings are NOT stored here —
those live in ChromaDB (Yeshneil's retrieval layer).

Field design
~~~~~~~~~~~~
All status/source_type values are stored as plain VARCHAR strings whose
allowed values are enforced at the application layer via the Pydantic
``ResourceStatus`` and ``SourceType`` enums (app.schemas.common).
SQLite does not have a native ENUM column type, and adding a CHECK
constraint here would duplicate the Pydantic validation without adding
safety — so we keep the column as String and rely on the service layer
to pass only valid enum values.

Timestamps
~~~~~~~~~~
Both ``created_at`` and ``updated_at`` are stored as UTC datetimes.
``updated_at`` is automatically refreshed by the ``update_resource_status``
CRUD function — it is NOT handled by a DB-level trigger (SQLite has limited
trigger support and we avoid the complexity at this stage).

TODO(pranav/pannaga): add Alembic migrations before any production
    deployment so schema changes can be applied without dropping data.
TODO(pannaga): add an index on ``status`` and ``source_type`` once the
    archive list query runs against real data — may become a hot read path.
"""

from __future__ import annotations

from datetime import datetime

from app.database.base import Base
from sqlalchemy import DateTime, String, Text
from sqlalchemy.orm import Mapped, mapped_column


class Resource(Base):
    """
    ORM model for the ``resources`` table.

    Each row represents one ingested resource (URL or PDF). The service
    layer (app.services) is the only caller of CRUD functions that read
    or write this table — routes must never import this model directly.

    Columns
    -------
    resource_id : str
        Primary key. Format: "res_<ulid>" (e.g. "res_01j9k3m7xp...").
        Generated by the service layer; not auto-incremented by the DB.
    title : str | None
        Human-readable title. Null until the AI pipeline extracts one.
    source_type : str
        "url" or "pdf". Stored as a plain string; enum enforced in service.
    status : str
        "pending" | "processing" | "ready" | "failed". Starts as "pending".
    summary : str | None
        AI-generated summary. Null until the summarization step completes.
    source_url : str | None
        Original URL for URL-sourced resources. Null for PDFs.
    filename : str | None
        Original filename for PDF uploads. Null for URL-sourced resources.
    error_message : str | None
        Human-readable pipeline failure reason. Null unless status="failed".
        Set by the service layer when it catches a pipeline exception.
        Safe for logging and display — must never contain secrets or traces.
    created_at : datetime
        UTC timestamp set once on creation. Never updated.
    updated_at : datetime
        UTC timestamp updated whenever status or metadata changes.
    completed_at : datetime | None
        UTC timestamp set once when pipeline processing finishes (status
        transitions to "ready" or "failed"). Null while pending/processing.
    """

    __tablename__ = "resources"

    resource_id: Mapped[str] = mapped_column(
        String(64),
        primary_key=True,
        index=True,
        comment="Stable resource identifier. Format: res_<ulid>.",
    )
    title: Mapped[str | None] = mapped_column(
        String(512),
        nullable=True,
        comment="Extracted or inferred title. Null until AI extraction completes.",
    )
    source_type: Mapped[str] = mapped_column(
        String(16),
        nullable=False,
        comment="'url' or 'pdf'. Enum enforced at the application layer.",
    )
    status: Mapped[str] = mapped_column(
        String(16),
        nullable=False,
        default="pending",
        comment="'pending' | 'processing' | 'ready' | 'failed'.",
    )
    summary: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="AI-generated summary. Null until summarization completes.",
    )
    source_url: Mapped[str | None] = mapped_column(
        String(2048),
        nullable=True,
        comment="Original HTTP/HTTPS URL. Null for PDF uploads.",
    )
    filename: Mapped[str | None] = mapped_column(
        String(512),
        nullable=True,
        comment="Original PDF filename from the UploadFile. Null for URL uploads.",
    )
    error_message: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Pipeline failure reason. Non-null only when status='failed'.",
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        nullable=False,
        comment="UTC creation timestamp. Set once; never updated.",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        nullable=False,
        comment="UTC last-modified timestamp. Updated on any status/metadata change.",
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime,
        nullable=True,
        comment="UTC timestamp when pipeline finished (ready or failed). Null while pending/processing.",
    )

    def __repr__(self) -> str:
        return (
            f"Resource("
            f"resource_id={self.resource_id!r}, "
            f"source_type={self.source_type!r}, "
            f"status={self.status!r}"
            f")"
        )
